import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Cherry",
      email: "cherry123@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Alvin",
      email: "alvin123@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Versace Comforter Set",
      category: "Bed set",
      image: "/images/p6.jpg",
      price: 75,
      countInStock: 20,
      brand: "Versace",
      rating: 4,
      numReviews: 9,
      description: "high quality product",
    },

    {
      name: "Duvet Sheet Set",
      category: "Bed Sheet",
      image: "/images/p8.jpg",
      price: 139,
      countInStock: 15,
      brand: "brooklinen",
      rating: 4.2,
      numReviews: 8,
      description: "high quality product",
    },

    {
      name: "Essential Silky Sheet Set",
      category: "Bed Sheet",
      image: "/images/p2.jpg",
      price: 129,
      countInStock: 35,
      brand: "Resident",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Burberry Comforter Set",
      category: "Bed Set",
      image: "/images/p3.jpg",
      price: 120,
      countInStock: 0,
      brand: "Burberry",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Dior luxury Comforter Set",
      category: "bed Set",
      image: "/images/p5.jpg",
      price: 150,
      countInStock: 20,
      brand: "Dior",
      rating: 5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Bobble Knit Pillow Covers",
      category: "Pillow Covers",
      image: "/images/p7.jpg",
      price: 99,
      countInStock: 20,
      brand: "West elm",
      rating: 5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};
export default data;
