import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Cherry",
      email: "cherry123@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Alvin",
      email: "alvin123@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Yarn Dye Healther 3-pc",
      category: "Stripes Comforter Set",
      image: "/images/s1.jpg",
      price: 131.25,
      countInStock: 20,
      brand: "Fieldcrest",
      rating: 4,
      numReviews: 9,
      description: "high quality product",
    },

    {
      name: "Luxury Scroll Woven Jacquard 3-pc",
      category: "Comforter Set",
      image: "/images/s2.jpg",
      price: 139,
      countInStock: 15,
      brand: "Fieldcrest",
      rating: 4.2,
      numReviews: 8,
      description: "high quality product",
    },

    {
      name: "complete bedding sheet",
      category: "Bed Sheet",
      image: "/images/s3.jpg",
      price: 129,
      countInStock: 35,
      brand: "Home Expression",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Velvet Plush Plush",
      category: "Throw Blanket",
      image: "/images/s5.jpg",
      price: 95,
      countInStock: 0,
      brand: "JC",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "All Over Shag Fur Square",
      category: "throw pillow",
      image: "/images/s4.jpg",
      price: 150,
      countInStock: 20,
      brand: "Home Express",
      rating: 5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Bobble Knit Pillow Covers",
      category: "Pillow Covers",
      image: "/images/p7.jpg",
      price: 99,
      countInStock: 20,
      brand: "West elm",
      rating: 5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};
export default data;
