 const data = {
    products: [
        {   _id: '1',
            name: 'Versace Comforter Set',
            catgory: 'Bed set',
            image: '/images/p6.jpg',
            price: 75,
            countInStock: 20,
            brand: 'Versace',
            rating: 4,
            numReviews: 9,
            description: 'high quality product',
        },

        {
            _id: '2',
            name: 'Duvet Sheet Set',
            catgory: 'Bed Sheet',
            image: '/images/p8.jpg',
            price: 139,
            countInStock: 15,
            brand: 'brooklinen',
            rating: 4.2,
            numReviews: 8,
            description: 'high quality product',
        },

        {
            _id: '3',
            name: 'Essential Silky Sheet Set',
            catgory: 'Bed Sheet',
            image: '/images/p2.jpg',
            price: 129,
            countInStock: 35,
            brand: 'Resident',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Burberry Comforter Set',
            catgory: 'Bed Set',
            image: '/images/p3.jpg',
            price: 120,
            countInStock: 0,
            brand: 'Burberry',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Dior luxury Comforter Set',
            catgory: 'bed Set',
            image: '/images/p5.jpg',
            price: 150,
            countInStock: 20,
            brand: 'Dior',
            rating: 5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Bobble Knit Pillow Covers',
            catgory: 'Pillow Covers',
            image: '/images/p7.jpg',
            price: 99,
            countInStock: 20,
            brand: 'West elm',
            rating: 5,
            numReviews: 10,
            description: 'high quality product',
        },
    ],
};
export default data;