 const data = {
    products: [
        {   _id: '1',
            name: 'Floral Pintuck Comforter Set',
            catgory: 'Bed set',
            image: '/images/p1.jpg',
            price: 75,
            countInStock: 20,
            brand: 'Madison',
            rating: 4,
            numReviews: 9,
            description: 'high quality product',
        },

        {
            _id: '2',
            name: 'Classic Core Sheet Set',
            catgory: 'Bed Sheet',
            image: '/images/p9.jpg',
            price: 139,
            countInStock: 15,
            brand: 'brooklinen',
            rating: 4.2,
            numReviews: 8,
            description: 'high quality product',
        },

        {
            _id: '3',
            name: 'Essential Cotton Sheet Set',
            catgory: 'Bed Sheet',
            image: '/images/p6.jpg',
            price: 129,
            countInStock: 35,
            brand: 'Resident',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: '3D Oil Red Rose Comforter Set',
            catgory: 'Bed Set',
            image: '/images/p4.jpg',
            price: 120,
            countInStock: 15,
            brand: 'EsyDream',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Dior luxury Comforter Set',
            catgory: 'bed Set',
            image: '/images/p5.jpg',
            price: 150,
            countInStock: 20,
            brand: 'Dior',
            rating: 5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Bobble Knit Pillow Covers',
            catgory: 'Pillow Covers',
            image: '/images/p7.jpg',
            price: 99,
            countInStock: 20,
            brand: 'West elm',
            rating: 5,
            numReviews: 10,
            description: 'high quality product',
        },
    ],
};
export default data;